name: autonomy_flutter
description: Autonomy cross platform

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.26.0+20

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  after_layout: ^1.2.0
  async: ^2.8.2
  bubble: ^1.2.1
  cached_network_image: ^3.2.1
  cast: ^1.1.0
  collection: ^1.15.0
  connectivity_plus: ^2.2.1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^3.2.1
  dio: ^4.0.6
  dio_smart_retry: ^1.2.0
  easy_debounce: ^2.0.2+1
  ecdsa: ^0.0.4
  fast_base58: ^0.2.1
  floor: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_blue:
    git:
      url: https://github.com/autonomy-system/flutter_blue.git
      ref: 4f1f28c7bab5596afa6fa175f81c3a953f7c993f
  flutter_cache_manager: ^3.3.0
  flutter_chat_types: ^3.3.1
  flutter_chat_ui: ^1.6.4
  flutter_dotenv: ^5.0.2
  flutter_downloader:
    git:
      url: https://github.com/autonomy-system/flutter_downloader
      ref: 0b047c6fc539df5e00be03a87ce598e4ef71005f
  flutter_email_sender: ^5.1.0
  flutter_fgbg: ^0.2.0
  flutter_image_compress: ^1.1.0
  flutter_markdown: ^0.6.9
  flutter_native_splash: ^2.0.5
  flutter_slidable: ^1.2.0
  flutter_svg: ^1.1.5
  flutter_to_airplay:
    git:
      url: https://github.com/autonomy-system/flutter_to_airplay.git
      ref: 0bd6ff556a664d3f8881f1a570f4d2028b7101dd
  flutter_vibrate: ^1.3.0
  get_it: ^7.2.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  http: ^0.13.2
  image_picker: ^0.8.4+9
  in_app_purchase: ^3.0.6
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  jiffy: ^5.0.0
  flutter_keyboard_visibility: ^5.3.0
  libauk_dart:
    git:
      url: https://github.com/autonomy-system/libauk-dart.git
      ref: fe109599472c5c9518d03001784b0a51bf24f644
  local_auth: ^2.1.0
  logging: ^1.0.2
  mime: ^1.0.1
  modal_bottom_sheet: ^2.0.0
  nft_rendering:
    git:
      url: https://github.com/autonomy-system/nft-rendering.git
      ref: v1.0.11
  onesignal_flutter: ^3.3.0
  open_settings: ^2.0.2
  overlay_support: ^2.0.0
  package_info_plus: ^1.4.0
  page_transition: ^2.0.5
  path_provider: ^2.0.9
  permission_handler: ^10.0.0
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  retrofit: null
  roundcheckbox: ^2.0.4+1
  sentry_dio: ^6.4.0
  sentry_flutter: ^6.4.0
  shake: ^2.0.0
  share: ^2.0.4
  shared_preferences: ^2.0.0
  syncfusion_flutter_pdfviewer: ^20.1.57-beta
  synchronized: ^3.0.0+2
  tezart:
    git:
      url: https://github.com/autonomy-system/tezart.git
      ref: 336d935c5f376afc0a21dac9c7061d3cdee6c047
  uni_links: ^0.5.1
  url_launcher: ^6.0.20
  uuid: ^3.0.5
  video_player: ^2.4.2
  wakelock: ^0.6.1+2
  wallet_connect:
    git:
      url: https://github.com/autonomy-system/wallet-connect-dart.git
      ref: 60919193f36ae4f026dfdebe929d1a1ab0d23d29
  web3dart: ^2.3.3
  web_socket_channel: ^2.1.0
  webview_flutter: ^3.0.0
  json_annotation: ^4.6.0
  iso_duration_parser: ^1.1.1
  autonomy_theme:
    git:
      url: https://github.com/bitmark-inc/autonomy-client-shared-theme.git
      ref: 1.0.3

  easy_localization: ^3.0.1
  rxdart: ^0.26.0
  in_app_review: ^2.0.4
  nft_collection:
    git:
      url: https://github.com/autonomy-system/nft-collection
      ref: a5a52d95c3510086fc3b7fd7e8e65631f4036303
  flutter_branch_sdk: ^6.1.0
  flutter_rating_bar: ^4.0.1
  metric_client:
    git:
      url: https://github.com/autonomy-system/metric-client-dart
      ref: ec37709d6f7a3901e3bd4238ba178205a88f6261
  dotenv: ^4.0.1

dependency_overrides:
  cached_network_image: 3.2.1
  syncfusion_flutter_pdfviewer: 20.2.46-beta
  # Error using when import photo_view from dependencies:
  # https://stackoverflow.com/questions/70404718/error-with-photoview-looking-up-a-deactivated-widgets-ancestor-is-unsafe/71010204#71010204
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: c5fcfd

dev_dependencies:
  flutter_lints: null
  build_runner: null
  built_value_generator: null
  floor_generator: null
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  appium_driver: ^0.5.2
  json_serializable: null
  mockito: null
  retrofit_generator: null
  test: null

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/erc721-abi.json
    - assets/erc1155-abi.json
    - assets/images/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AtlasGrotesk
      fonts:
        - asset: assets/fonts/AtlasGrotesk/AtlasGrotesk-Regular.otf
        - asset: assets/fonts/AtlasGrotesk/AtlasGrotesk-Light.otf
        - asset: assets/fonts/AtlasGrotesk/AtlasGrotesk-Medium.otf
        - asset: assets/fonts/AtlasGrotesk/AtlasGrotesk-Bold.otf
          weight: 700
    - family: DomaineSansText
      fonts:
        - asset: assets/fonts/DomaineSansText/DomaineSansText-Regular.otf
    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono/IBMPlexMono-Regular.ttf
        - asset: assets/fonts/IBMPlexMono/IBMPlexMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexMono/IBMPlexMono-SemiBold.ttf
