name: autonomy_flutter
description: Autonomy cross platform

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.36.0+121

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  after_layout: ^1.2.0
  bs58check: ^1.0.2
  bubble: ^1.2.1
  cached_network_image: ^3.2.1
  carousel_slider: ^5.0.0
  collection: ^1.15.0
  confetti: ^0.7.0
  connectivity_plus:
  crypto: ^3.0.5
  device_info_plus: ^10.1.2
  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  easy_debounce: ^2.0.2+1
  fast_base58: ^0.2.1
  floor: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_cache_manager: ^3.3.0
  flutter_chat_types: ^3.3.1
  flutter_chat_ui: ^1.6.4
  flutter_dotenv: ^5.0.2
  flutter_downloader:
    git:
      url: https://github.com/autonomy-system/flutter_downloader
      ref: 965d4acdfd73deeee64ed69ac2cf36b6017f749b
  flutter_fgbg: ^0.3.0
  flutter_image_compress: ^2.0.4
  flutter_markdown: ^0.6.9
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  flutter_vibrate: ^1.3.0
  geolocator: ^9.0.2
  get_it: ^7.2.0
  gif_view: ^0.4.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  http: ^1.1.0
  image_picker: ^1.0.1
  in_app_purchase: ^3.2.0
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.0
  jiffy: ^6.2.1
  flutter_keyboard_visibility: ^6.0.0
  libauk_dart:
    git:
      url: https://github.com/autonomy-system/libauk-dart.git
      ref: e2b571cd2e297efb62e40a0e9a606225e2f7386e
  local_auth: ^2.2.0
  logging: ^1.2.0
  measured_size: ^1.0.0
  mime: ^1.0.1
  onesignal_flutter: ^3.3.0
  open_settings: ^2.0.2
  overlay_support: ^2.0.0
  package_info_plus: ^8.0.3
  page_transition: ^2.0.5
  path_provider: ^2.1.1
  permission_handler: ^10.0.0
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  retrofit: null
  roundcheckbox: ^2.0.4+1
  sentry_dio: ^8.9.0
  sentry_flutter: ^8.9.0
  shake: ^2.0.0
  share_plus: ^10.0.3
  shared_preferences: ^2.0.0
  synchronized: ^3.0.0+2
  social_share: ^2.3.1
  system_date_time_format:
  tezart:
    git:
      url: https://github.com/autonomy-system/tezart.git
      ref: 341a6de46324d38f420334f148342c2e1655b3c0
  app_links: ^6.3.2
  url_launcher: ^6.2.2
  uuid:
  web3dart: ^2.5.1
  web_socket_channel:
  json_annotation: ^4.9.0
  iso_duration_parser: ^1.1.1
  feralfile_app_theme:
    git:
      url: https://github.com/bitmark-inc/feralfile-app-client-shared-theme
      ref: 8d791a051a9b38791e82ac1582176d1b4e8e74fa
  markdown: ^7.1.1
  easy_localization: ^3.0.1
  rxdart: ^0.27.1
  in_app_review: ^2.0.4
  nft_collection:
    git:
      url: https://github.com/autonomy-system/nft-collection
      ref: 1a281ef3b56bef685a50e7d5099c8aab13314440
  flutter_branch_sdk: ^7.0.2
  flutter_rating_bar: ^4.0.1
  multi_value_listenable_builder: ^0.0.2
  auto_size_text: ^3.0.0
  uri: ^1.0.0
  undo: ^1.4.0
  reorderable_grid_view: ^2.2.5
  eth_sig_util:
    git:
      url: https://github.com/autonomy-system/eth-sig-util.git
      ref: 15334dee6a5bbd3047ce3af2bdd061906a2094e2
  flutter_widget_from_html: ^0.10.3
  readmore: ^2.2.0
  elliptic: ^0.3.8
  sentry: ^8.9.0
  path: ^1.9.0
  in_app_purchase_storekit: ^0.3.14
  in_app_purchase_android: ^0.3.4
  convert: ^3.1.1
  sqflite: ^2.2.2
  slidable_button: ^3.0.0+1
  background_fetch: ^1.1.3
  image: ^4.2.0
  widgets_to_image: ^0.0.2
  geocoding: ^2.1.0
  flutter_inappwebview: ^6.1.5
  webview_flutter: ^4.9.0
  html: ^0.15.1
  video_player: ^2.9.2
  walletconnect_flutter_v2: ^2.1.11
  awesome_notifications: ^0.8.3
  shimmer: ^3.0.0
  graphql_flutter:
  card_swiper: ^3.0.1
  marqueer: ^1.2.0
  image_gallery_saver: ^2.0.3
  hand_signature: ^3.0.1
  flutter_pdfview: ^1.3.2
  network_info_plus: ^6.0.1
  backdrop: ^0.9.1
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.2
  flutter_app_badger: ^1.5.0
  wakelock_plus: ^1.2.8
  model_viewer_plus: 1.6.1
  audio_session: ^0.1.10
  just_audio: ^0.9.29
  xml: ^6.1.0
  vector_graphics_compiler: ^1.1.7
  passkeys: ^2.0.8
  home_widget: ^0.7.0
  workmanager: ^0.5.2


dependency_overrides:
  intl: 0.18.0
  archive: ^3.6.1
  package_info_plus: ^8.0.3
  frontend_server_client: ^4.0.0
  webview_flutter_android: 3.16.1

dev_dependencies:
  flutter_lints: null
  build_runner: null
  built_value_generator: null
  floor_generator: null
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  appium_driver: ^0.6.0
  json_serializable: null
  mockito: null
  retrofit_generator: null
  test: null
  dependency_validator: null
  dotenv: ^4.0.1
  html_unescape: ^2.0.0
  sentry_dart_plugin: ^2.1.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/erc20-abi.json
    - assets/erc721-abi.json
    - assets/erc1155-abi.json
    - assets/images/
    - assets/translations/
    - assets/videos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PPMori
      fonts:
        - asset: assets/fonts/PPMori/PPMori-Regular.ttf
        - asset: assets/fonts/PPMori/PPMori-Bold.ttf
        - asset: assets/fonts/PPMori/PPMori-SemiBold.ttf

    - family: AuIcon
      fonts:
        - asset: assets/fonts/AuIcon.ttf

    - family: FFIcon
      fonts:
        - asset: assets/fonts/FFIcon.ttf

    - family: MoMASans
      fonts:
        - asset: assets/fonts/MoMASans/MoMA-Sans-Bold.otf
        - asset: assets/fonts/MoMASans/MoMA-Sans-Bold-Italic.otf
        - asset: assets/fonts/MoMASans/MoMA-Sans-Regular.otf
        - asset: assets/fonts/MoMASans/MoMA-Sans-Regular-Italic.otf

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  project: autonomy-client-flutter
  org: bitmark-inc
  wait_for_processing: false
  log_level: info
  commits: auto
  ignore_missing: true