name: autonomy_flutter
description: Autonomy cross platform

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.26.0+20

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  after_layout: ^1.2.0
  async: ^2.8.2
  aws_cognito_identity_api: ^1.2.0
  aws_firehose_api: ^1.2.0
  bubble: ^1.2.1
  cached_network_image: ^3.2.1
  cast: ^1.1.0
  collection: ^1.15.0
  connectivity_plus: ^2.2.1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^3.2.1
  dio: ^4.0.6
  dio_smart_retry: ^1.2.0
  easy_debounce: ^2.0.2+1
  ecdsa: ^0.0.4
  fast_base58: ^0.2.1
  floor: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_blue:
    git:
      url: https://github.com/autonomy-system/flutter_blue.git
      ref: 4f1f28c7bab5596afa6fa175f81c3a953f7c993f
  flutter_chat_types: ^3.3.1
  flutter_chat_ui: ^1.5.8
  flutter_dotenv: ^5.0.2
  flutter_downloader: ^1.8.0
  flutter_email_sender: ^5.1.0
  flutter_fgbg: ^0.2.0
  flutter_image_compress: ^1.1.0
  flutter_markdown: ^0.6.9
  flutter_native_splash: ^2.0.5
  flutter_slidable: ^1.2.0
  flutter_svg:
    git:
      url: https://github.com/autonomy-system/flutter_svg.git
      ref: dfe0828aec39169276cc2722e016a2dbaa95baee
  flutter_to_airplay:
    git:
      url: https://github.com/autonomy-system/flutter_to_airplay.git
      ref: 0bd6ff556a664d3f8881f1a570f4d2028b7101dd
  flutter_vibrate: ^1.3.0
  get_it: ^7.2.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  http: ^0.13.2
  image_picker: ^0.8.4+9
  in_app_purchase: ^3.0.5
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  jiffy: ^5.0.0
  libauk_dart:
    git:
      url: https://github.com/autonomy-system/libauk-dart.git
      ref: 34b6347f71698e797f9a8ab8c3f883ba4b63d1b0
  local_auth: ^2.1.0
  logging: ^1.0.2
  mime: ^1.0.1
  modal_bottom_sheet: ^2.0.0
  nft_rendering:
    git:
      url: git@github.com:autonomy-system/nft-rendering.git
      ref: v1.0.2
  onesignal_flutter: ^3.3.0
  open_settings: ^2.0.2
  overlay_support: ^2.0.0
  package_info_plus: ^1.4.0
  page_transition: ^2.0.5
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  receive_sharing_intent: ^1.4.5
  retrofit: null
  roundcheckbox: ^2.0.4+1
  sentry_dio: ^6.4.0
  sentry_flutter: ^6.4.0
  shake: ^2.0.0
  share_plus: ^4.0.10
  shared_preferences: ^2.0.0
  syncfusion_flutter_pdfviewer: ^20.1.57-beta
  tezart:
    git:
      url: https://github.com/autonomy-system/tezart.git
      ref: v1.0.3
  uni_links: ^0.5.1
  url_launcher: ^6.0.20
  uuid: ^3.0.5
  video_player: ^2.4.2
  wakelock: ^0.6.1+2
  wallet_connect:
    git:
      url: https://github.com/autonomy-system/wallet-connect-dart.git
      ref: 60919193f36ae4f026dfdebe929d1a1ab0d23d29
  web3dart: ^2.3.3
  web_socket_channel: ^2.1.0
  webview_flutter: ^3.0.0

dependency_overrides:
  # Error using when import photo_view from dependencies:
  # https://stackoverflow.com/questions/70404718/error-with-photoview-looking-up-a-deactivated-widgets-ancestor-is-unsafe/71010204#71010204
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: c5fcfd

dev_dependencies:
  build_runner: null
  built_value_generator: null
  floor_generator: null
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: null
  mockito: null
  retrofit_generator: null
  test: null

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/erc721-abi.json
    - assets/images/arrow.svg
    - assets/images/arrow_2.svg
    - assets/images/penrose.svg
    - assets/images/penrose_appcenter.svg
    - assets/images/lock_penrose.svg
    - assets/images/lock_penrose_appcenter.png
    - assets/images/penrose_onboarding.png
    - assets/images/penrose_onboarding_appcenter.png
    - assets/images/guidedPenrose.svg
    - assets/images/hamburgerIcon.svg
    - assets/images/iconQr.svg
    - assets/images/iconEth.svg
    - assets/images/iconUsd.svg
    - assets/images/iconXtz.svg
    - assets/images/iconBitmark.svg
    - assets/images/iconClose.svg
    - assets/images/iconReceive.svg
    - assets/images/iconCloudOff.svg
    - assets/images/iconCustomerSupport.svg
    - assets/images/iconForward.svg
    - assets/images/iconFeed.svg
    - assets/images/iconInfo.svg
    - assets/images/iconSharpFeedback.svg
    - assets/images/cil_external-link.svg
    - assets/images/tezos_social_icon.svg
    - assets/images/feralfileAppIcon.svg
    - assets/images/autonomyIcon.png
    - assets/images/rainbow.png
    - assets/images/iconLedger.svg
    - assets/images/trust-alternative.png
    - assets/images/metamask-alternative.png
    - assets/images/walletconnect-alternative.png
    - assets/images/kukai_wallet.png
    - assets/images/temple_wallet.png
    - assets/images/tezos_wallet.png
    - assets/images/premium_comparation.svg
    - assets/images/premium_comparation_light.svg
    - assets/images/face_id.svg
    - assets/images/touch_id.svg
    - assets/images/cloudOff.svg
    - assets/images/cloudOn.svg
    - assets/images/cloudEncryption.svg
    - assets/images/nav-arrow-left.svg
    - assets/images/image_error.svg
    - assets/images/chromecast.svg
    - assets/images/notification_onboarding.svg
    #   - images/a_dot_ham.jpeg
    - assets/images/joinFile.svg
    - assets/images/sendMessage.svg
    - assets/images/sendMessageFilled.svg
    - assets/images/icloudKeychainGuide.svg
    - assets/images/chatFileIcon.png
    - assets/images/radio_unselected.svg
    - assets/images/radio_selected.svg
    - assets/images/tezos_tx_sent.svg
    - assets/images/tezos_tx_received.svg
    - assets/images/tezos_tx_smartcontract.svg
    - assets/images/external_link.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AtlasGrotesk
      fonts:
        - asset: fonts/AtlasGrotesk/AtlasGrotesk-Regular.otf
        - asset: fonts/AtlasGrotesk/AtlasGrotesk-Light.otf
        - asset: fonts/AtlasGrotesk/AtlasGrotesk-Bold.otf
          weight: 700
    - family: DomaineSansText
      fonts:
        - asset: fonts/DomaineSansText/DomaineSansText-Regular.otf
    - family: IBMPlexMono
      fonts:
        - asset: fonts/IBMPlexMono/IBMPlexMono-Regular.ttf
        - asset: fonts/IBMPlexMono/IBMPlexMono-Bold.ttf
          weight: 700
        - asset: fonts/IBMPlexMono/IBMPlexMono-SemiBold.ttf
